# Generated by Django 5.0.6 on 2024-07-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movies', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('genre', models.CharField(max_length=200)),
                ('rating', models.FloatField()),
                ('one_line', models.CharField(max_length=200)),
                ('stars', models.CharField(max_length=200)),
                ('votes', models.IntegerField()),
                ('run_time', models.IntegerField()),
                ('gross', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
    ]
