# Generated by Django 5.0.6 on 2024-07-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0003_alter_data_gross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='gross',
            field=models.FloatField(),
        ),
    ]
