# Generated by Django 5.0.6 on 2024-07-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charts', '0004_alter_data_gross'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='run_time',
            field=models.CharField(max_length=200),
        ),
    ]
